import driver from "./assets/drivers/1.png";
import client from "./assets/drivers/2.png";
import vehicle from "./assets/vehicle.png";
import transfer from "./assets/transfer.png";
import chat from "./assets/chat.png";
import chat2 from "./assets/chat/chat 2.png";
import chat3 from "./assets/chat/chat 3.png";
import chat4 from "./assets/chat/chat 4.png";
import chat5 from "./assets/chat/chat 5.png";
export const data = [
  {
    Name: "John Smith",
    Image: driver,
    License: "Gb28632814",
    Transfers: "210",
    Car: "MP134",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Image: driver,
    License: "Gb28632814",
    Transfers: "210",
    Car: "MP134",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Image: driver,
    License: "Gb28632814",
    Transfers: "210",
    Car: "MP134",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Image: driver,
    License: "Gb28632814",
    Transfers: "210",
    Car: "MP134",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Image: driver,
    License: "Gb28632814",
    Transfers: "210",
    Car: "MP134",
    Status: "Active",
  },
  // Add more data as needed
];
export const clientData = [
  {
    Name: "John Smith",
    Image: client,
    Phone: "+1 (23) 456 7890",

    Transfers: "30",
    Revenue: "$2.3K",
    Email: "mail@gmail.com",
  },
  {
    Name: "John Smith",
    Image: client,
    Phone: "+1 (23) 456 7890",

    Transfers: "30",
    Revenue: "$2.3K",
    Email: "mail@gmail.com",
  },
  {
    Name: "John Smith",
    Image: client,
    Phone: "+1 (23) 456 7890",

    Transfers: "30",
    Revenue: "$2.3K",
    Email: "mail@gmail.com",
  },
  {
    Name: "John Smith",
    Image: client,
    Phone: "+1 (23) 456 7890",

    Transfers: "30",
    Revenue: "$2.3K",
    Email: "mail@gmail.com",
  },
  {
    Name: "John Smith",
    Image: client,
    Phone: "+1 (23) 456 7890",

    Transfers: "30",
    Revenue: "$2.3K",
    Email: "mail@gmail.com",
  },
];
export const Driverdata = [
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612731",
    CarNumber: "MP137",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612732",
    CarNumber: "MP138",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612733",
    CarNumber: "MP139",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612734",
    CarNumber: "MP140",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612735",
    CarNumber: "MP141",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612736",
    CarNumber: "MP142",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612737",
    CarNumber: "MP143",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612738",
    CarNumber: "MP144",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612739",
    CarNumber: "MP145",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612740",
    CarNumber: "MP146",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612741",
    CarNumber: "MP147",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612742",
    CarNumber: "MP148",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612743",
    CarNumber: "MP149",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612744",
    CarNumber: "MP150",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612745",
    CarNumber: "MP151",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612746",
    CarNumber: "MP152",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612747",
    CarNumber: "MP153",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612748",
    CarNumber: "MP154",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612749",
    CarNumber: "MP155",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612750",
    CarNumber: "MP156",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612751",
    CarNumber: "MP157",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612752",
    CarNumber: "MP158",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612753",
    CarNumber: "MP159",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612754",
    CarNumber: "MP160",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612755",
    CarNumber: "MP161",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612756",
    CarNumber: "MP162",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612757",
    CarNumber: "MP163",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612758",
    CarNumber: "MP164",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612759",
    CarNumber: "MP165",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612760",
    CarNumber: "MP166",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612761",
    CarNumber: "MP167",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612762",
    CarNumber: "MP168",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612763",
    CarNumber: "MP169",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612764",
    CarNumber: "MP170",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612765",
    CarNumber: "MP171",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612766",
    CarNumber: "MP172",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612767",
    CarNumber: "MP173",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612768",
    CarNumber: "MP174",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612769",
    CarNumber: "MP175",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612770",
    CarNumber: "MP176",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612771",
    CarNumber: "MP177",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612772",
    CarNumber: "MP178",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612773",
    CarNumber: "MP179",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612774",
    CarNumber: "MP180",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612775",
    CarNumber: "MP181",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612776",
    CarNumber: "MP182",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612777",
    CarNumber: "MP183",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612778",
    CarNumber: "MP184",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612779",
    CarNumber: "MP185",
    Transfers: "210",
    Status: "Active",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    DriverLicense: "BH23612780",
    CarNumber: "MP186",
    Transfers: "210",
    Status: "Active",
  },
];
export const Clientdata = [
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
  {
    Name: "John Smith",
    Phone: "+1 (23) 456 7890",
    Image: driver,
    Address: "2365 Lawman Avenue",
    EmailAddress: "email@gmail.com",
    Revenue: "$3.5k",
    Transfers: "210",
  },
];
export const ClientTransfers = [
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Talan Calzoni",
    Image: client,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
  {
    Name: "Lydia Westervelt",
    Image: driver,
    Date: "10-29-23",
    Time: "10:30 AM",
    PickupLocation: "8 Lawman Avenue",
    DestinationLocation: "56 Lawman Avenue",
    CarNumber: "MP134",
    Status: "Completed",
  },
];
export const vehicles = [
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "On Way ",
  },
  {
    Name: "Black Luci",
    Image: vehicle,
    License: "JB68321369",
    Driver: "Aspen Workman",
    CarNumber: "MH7901",
    Status: "Parking",
  },
];
export const transfers = [
  {
    Id: 1,
    Name: "Talan Calzoni",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Aspen Workman",
    Status: "Pending",
    Image: transfer,
  },
  {
    Id: 2,
    Name: "Talan Press",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Lydia Rosser",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 3,
    Name: "Lydia Westervelt",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Maria Mango",
    Status: "Pending",
    Image: transfer,
  },
  {
    Id: 4,
    Name: "Lindsey Aminoff",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Omar Philips",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 5,
    Name: "Tiana Ekstrom",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Jaylon Saris",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 6,
    Name: "Lydia Levin",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Gretchen Bergson",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 7,
    Name: "Phillip Korsgaard",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Kianna Botosh",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 8,
    Name: "Kadin Bergson",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Abram Vaccaro",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 9,
    Name: "Giana Vetrovs",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Angel Lipshutz",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 10,
    Name: "Marilyn Saris",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Charlie Bergson",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 7,
    Name: "Phillip Korsgaard",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Kianna Botosh",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 8,
    Name: "Kadin Bergson",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Abram Vaccaro",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 9,
    Name: "Giana Vetrovs",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Angel Lipshutz",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 10,
    Name: "Marilyn Saris",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Charlie Bergson",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 7,
    Name: "Phillip Korsgaard",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Kianna Botosh",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 8,
    Name: "Kadin Bergson",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Abram Vaccaro",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 9,
    Name: "Giana Vetrovs",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Angel Lipshutz",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 10,
    Name: "Marilyn Saris",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Charlie Bergson",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 7,
    Name: "Phillip Korsgaard",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Kianna Botosh",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 8,
    Name: "Kadin Bergson",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Abram Vaccaro",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 9,
    Name: "Giana Vetrovs",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Angel Lipshutz",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 10,
    Name: "Marilyn Saris",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Charlie Bergson",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 7,
    Name: "Phillip Korsgaard",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Kianna Botosh",
    Status: "Completed",
    Image: transfer,
  },
  {
    Id: 8,
    Name: "Kadin Bergson",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Abram Vaccaro",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 9,
    Name: "Giana Vetrovs",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Angel Lipshutz",
    Status: "Canceled",
    Image: transfer,
  },
  {
    Id: 10,
    Name: "Marilyn Saris",
    Date: "10-29-2023",
    Time: "10:30 AM",
    PickupLocation: "2365 Lawman Avenue",
    DestinationLocation: "2365 Lawman Avenue",
    AssignedDriver: "Charlie Bergson",
    Status: "Completed",
    Image: transfer,
  },
];
export const tip = [
  // {
  //   Id: 1,
  //   ClientName: "Charlie Kenter",
  //   Date: "29-10-2023",
  //   CarNumber: "Mi 790i",
  //   PickUpLocation: "2365 Leaman Avenue",
  //   DestinationLocation: "2365 Leaman Avenue",
  //   AssignedDriver: "Randy Workman",
  //   Status: "Completed",
  //   Image: driver,
  //   TipAmount: "$85",
  // },
  {
    Id: 2,
    ClientName: "Madelyn Ruiter",
    Date: "29-10-2023",
    CarNumber: "Mi 790i",
    PickUpLocation: "2365 Leaman Avenue",
    DestinationLocation: "2365 Leaman Avenue",
    AssignedDriver: "Carla Lukin",
    Status: "Completed",
    Image: driver,
    TipAmount: "$85",
  },
  {
    Id: 3,
    ClientName: "Ahmad Press",
    Date: "29-10-2023",
    CarNumber: "Mi 790i",
    PickUpLocation: "2365 Leaman Avenue",
    DestinationLocation: "2365 Leaman Avenue",
    AssignedDriver: "Alfonso Franci",
    Status: "Completed",
    Image: driver,
    TipAmount: "$85",
  },
  {
    Id: 4,
    ClientName: "Carla Lukin",
    Date: "29-10-2023",
    CarNumber: "Mi 790i",
    PickUpLocation: "2365 Leaman Avenue",
    DestinationLocation: "2365 Leaman Avenue",
    AssignedDriver: "Angel Salgados",
    Status: "Completed",
    Image: driver,
    TipAmount: "$85",
  },
];
export const customerData = [
  {
    name: "Marcus Baptista",
    type: "customer",
    image: chat2,
    messages: [
      {
        message: "Hey, how are you?",
        time: "August 12, 2024, 9:00 AM",
        isReceived: false,
      },
      {
        message: "Hey, how are you?",
        time: "August 15, 2024, 9:01 AM",
        isReceived: false,
      },
      {
        message: "Did you get the documents?",
        time: "August 15, 2024, 9:05 AM",
        isReceived: false,
      },
      {
        message: "Lorem ipsum dolor sit amet...",
        time: "August 15, 2024, 9:06 AM",
        isReceived: false,
      },
      {
        message: "I'm good, thanks! How about you?",
        time: "August 15, 2024, 9:02 AM",
        isReceived: true,
      },
      {
        message: "Yes, I got them. Thanks!",
        time: "August 15, 2024, 9:07 AM",
        isReceived: true,
      },
      {
        message: "Let's meet at 5 PM.",
        time: "August 15, 2024, 9:10 AM",
        isReceived: false,
      },
      {
        message: "5 PM works for me.",
        time: "August 15, 2024, 9:12 AM",
        isReceived: true,
      },
      {
        message: "Happy Birthday!",
        time: "August 15, 2024, 9:15 AM",
        isReceived: false,
      },
      {
        message: "Thank you so much!",
        time: "August 15, 2024, 9:17 AM",
        isReceived: true,
      },
      {
        message: "Can you send me the report?",
        time: "August 15, 2024, 9:20 AM",
        isReceived: false,
      },
      {
        message: "Sure, I'll send it by tomorrow.",
        time: "August 15, 2024, 9:22 AM",
        isReceived: true,
      },
      {
        message: "Did you get the documents?",
        time: "August 18, 2024, 10:10 AM",
        isReceived: false,
      },
    ],
  },
  {
    name: "Tommy Lee",
    type: "customer",
    image: chat4,
    messages: [
      {
        message: "Did you finish the project?",
        time: "August 12, 2024, 10:00 AM",
        isReceived: false,
      },
      {
        message: "Yes, I submitted it.",
        time: "August 15, 2024, 10:05 AM",
        isReceived: true,
      },
      {
        message: "Great job!",
        time: "August 15, 2024, 10:10 AM",
        isReceived: true,
      },
      {
        message: "Thanks!",
        time: "August 15, 2024, 10:15 AM",
        isReceived: false,
      },
      {
        message: "Let's talk tomorrow.",
        time: "August 16, 2024, 10:20 AM",
        isReceived: true,
      },
    ],
  },
  {
    name: "Sarah Williams",
    type: "customer",
    image: chat5,
    messages: [
      {
        message: "Hey Sarah, are you free?",
        time: "August 15, 2024, 11:00 AM",
        isReceived: false,
      },
      {
        message: "Yes, what's up?",
        time: "August 15, 2024, 11:05 AM",
        isReceived: true,
      },
      {
        message: "Can you review the presentation?",
        time: "August 15, 2024, 11:10 AM",
        isReceived: false,
      },
      {
        message: "I'll do that by noon.",
        time: "August 15, 2024, 11:12 AM",
        isReceived: true,
      },
      {
        message: "Thanks, I appreciate it!",
        time: "August 18, 2024, 11:20 AM",
        isReceived: false,
      },
    ],
  },
  {
    name: "Oliver Stone",
    type: "customer",
    image: chat,
    messages: [
      {
        message: "Any updates on the meeting?",
        time: "August 15, 2024, 2:00 PM",
        isReceived: false,
      },
      {
        message: "Yes, it's rescheduled to 3 PM.",
        time: "August 15, 2024, 2:10 PM",
        isReceived: true,
      },
      {
        message: "Alright, see you then.",
        time: "August 15, 2024, 2:15 PM",
        isReceived: false,
      },
      {
        message: "See you!",
        time: "August 15, 2024, 2:17 PM",
        isReceived: true,
      },
      {
        message: "Don't forget the report.",
        time: "August 19, 2024, 2:20 PM",
        isReceived: true,
      },
    ],
  },
  {
    name: "Emily Davis",
    type: "customer",
    image: chat2,
    messages: [
      {
        message: "Hey Emily, can we meet today?",
        time: "August 15, 2024, 3:00 PM",
        isReceived: false,
      },
      {
        message: "Sure, what time?",
        time: "August 15, 2024, 3:05 PM",
        isReceived: true,
      },
      {
        message: "How about 4 PM?",
        time: "August 15, 2024, 3:10 PM",
        isReceived: false,
      },
      {
        message: "4 PM works!",
        time: "August 15, 2024, 3:12 PM",
        isReceived: true,
      },
      {
        message: "See you at 4.",
        time: "August 20, 2024, 3:15 PM",
        isReceived: false,
      },
    ],
  },
];
export const driversData = [
  {
    name: "John Doe",
    type: "driver",
    image: chat4,
    messages: [
      {
        message: "Is the delivery on time?",
        time: "August 15, 2024, 7:00 AM",
        isReceived: false,
      },
      {
        message: "Yes, it will arrive at 9 AM.",
        time: "August 16, 2024, 7:05 AM",
        isReceived: true,
      },
      {
        message: "Great, thanks!",
        time: "August 17, 2024, 7:10 AM",
        isReceived: false,
      },
      {
        message: "You're welcome!",
        time: "August 18, 2024, 7:12 AM",
        isReceived: true,
      },
    ],
  },
  {
    name: "Alex Smith",
    type: "driver",
    image: chat,
    messages: [
      {
        message: "Any changes to the route?",
        time: "August 15, 2024, 8:15 AM",
        isReceived: false,
      },
      {
        message: "Yes, avoid 5th Ave.",
        time: "August 15, 2024, 8:20 AM",
        isReceived: true,
      },
      {
        message: "Got it, thanks!",
        time: "August 15, 2024, 8:22 AM",
        isReceived: false,
      },
      {
        message: "Drive safe!",
        time: "August 17, 2024, 8:25 AM",
        isReceived: true,
      },
    ],
  },
  {
    name: "Mary Johnson",
    type: "driver",
    image: chat3,
    messages: [
      {
        message: "Have you picked up the package?",
        time: "August 15, 2024, 9:00 AM",
        isReceived: false,
      },
      {
        message: "Yes, just picked it up.",
        time: "August 15, 2024, 9:05 AM",
        isReceived: true,
      },
      {
        message: "Perfect, thanks.",
        time: "August 15, 2024, 9:07 AM",
        isReceived: false,
      },
      {
        message: "No problem!",
        time: "August 19, 2024, 9:10 AM",
        isReceived: true,
      },
    ],
  },
  {
    name: "David Brown",
    type: "driver",
    image: chat2,
    messages: [
      {
        message: "What's the ETA?",
        time: "August 15, 2024, 10:00 AM",
        isReceived: false,
      },
      {
        message: "I'll be there by 11 AM.",
        time: "August 15, 2024, 10:05 AM",
        isReceived: true,
      },
      {
        message: "Okay, see you soon.",
        time: "August 15, 2024, 10:07 AM",
        isReceived: false,
      },
      {
        message: "See you!",
        time: "August 20, 2024, 10:10 AM",
        isReceived: true,
      },
    ],
  },
  {
    name: "Emma White",
    type: "driver",
    image: chat5,
    messages: [
      {
        message: "Is the truck loaded?",
        time: "August 15, 2024, 11:00 AM",
        isReceived: false,
      },
      {
        message: "Yes, all set to go.",
        time: "August 15, 2024, 11:05 AM",
        isReceived: true,
      },
      {
        message: "Perfect, thank you!",
        time: "August 15, 2024, 11:10 AM",
        isReceived: false,
      },
      {
        message: "You're welcome!",
        time: "August 28, 2024, 11:12 AM",
        isReceived: true,
      },
    ],
  },
];
export const reviewsData = [
  {
    name: "John Doe",
    rating: 5,
    review:
      "Great product! The quality is excellent and it works as described. I would definitely recommend it to others. The customer service was also very helpful and responsive. Overall, a fantastic experience.",
  },
  {
    name: "Jane Smith",
    rating: 4,
    review:
      "Good value for the price. The product meets my expectations and performs well. There were a few minor issues, but nothing major. I'm satisfied with my purchase and would consider buying again.",
  },
  {
    name: "Alice Johnson",
    rating: 3,
    review:
      "Average product. It works, but it's not anything special. There are some improvements needed in terms of durability and performance. It's okay for the price, but I wouldn't go out of my way to recommend it.",
  },
  {
    name: "Bob Brown",
    rating: 2,
    review:
      "Not great. The product didn't meet my expectations and had several issues. It felt cheaply made and didn't perform as advertised. Customer service was not very helpful. I wouldn't purchase this again.",
  },
  {
    name: "Emily Davis",
    rating: 5,
    review:
      "Exceptional product! Exceeded my expectations in every way. The build quality is top-notch and it performs flawlessly. Highly recommended for anyone looking for this type of product. Great job!",
  },
  {
    name: "Michael Wilson",
    rating: 4,
    review:
      "Very good product with a few minor flaws. It does what it's supposed to do and performs well overall. The price is reasonable, and I am happy with my purchase. Just a couple of small issues to note.",
  },
  {
    name: "Olivia Martinez",
    rating: 5,
    review:
      "Decent product but could use some improvements. It functions okay, but I noticed a few things that could be better. It's not a bad buy for the price, but it's not outstanding either.",
  },
  {
    name: "William Anderson",
    rating: 2,
    review:
      "Disappointing experience. The product had multiple issues and didn't live up to the description. The quality was poor, and it stopped working after a short time. Not worth the money.",
  },
  {
    name: "Sophia Taylor",
    rating: 5,
    review:
      "I am extremely pleased with this product. It exceeded all of my expectations in terms of performance and quality. The customer service was excellent, and I would definitely purchase from this seller again.",
  },
  {
    name: "James Harris",
    rating: 4,
    review:
      "Good product with only minor issues. It works well and performs as expected. There were a couple of small drawbacks, but they don't outweigh the overall positive experience. Worth the buy.",
  },
  {
    name: "Isabella Clark",
    rating: 3,
    review:
      "Product is okay but not great. It works, but there are some areas where it could be improved. For the price, it's acceptable, but I wouldn't necessarily recommend it to others.",
  },
  {
    name: "Jacob Lewis",
    rating: 2,
    review:
      "Not satisfied with this product. It had several problems and didn't meet my expectations. The quality was lacking, and it didn't function as advertised. I would not buy this again.",
  },
  {
    name: "Mia Walker",
    rating: 5,
    review:
      "Fantastic product! It works perfectly and the quality is exceptional. I am very happy with my purchase and the service I received. Highly recommended for anyone in the market for this type of product.",
  },
  {
    name: "Ethan Young",
    rating: 4,
    review:
      "Solid product with a few minor issues. It performs well and the quality is good. There were some small drawbacks, but overall, it's a good buy and I am satisfied with the purchase.",
  },
  {
    name: "Ava King",
    rating: 3,
    review:
      "The product is average. It does its job but lacks some features and quality improvements. For the price, it's okay, but don't expect anything extraordinary. It gets the job done.",
  },
  {
    name: "Liam Wright",
    rating: 2,
    review:
      "Not a great experience. The product had several issues and didn't perform well. The quality was subpar and it didn't meet my expectations. I would not recommend this to others.",
  },
  {
    name: "Charlotte Scott",
    rating: 5,
    review:
      "I am thrilled with this product. It exceeded all my expectations and works beautifully. The quality is top-notch and the customer service was outstanding. Definitely worth the purchase.",
  },
  {
    name: "Benjamin Green",
    rating: 4,
    review:
      "Good product overall. It works well and the quality is decent. There are a few minor issues, but they don't significantly impact the performance. I am pleased with the purchase.",
  },
  {
    name: "Amelia Adams",
    rating: 3,
    review:
      "It's an okay product. It does what it's supposed to do, but there are areas where it could be improved. For the price, it's acceptable, but it's not exceptional. It serves its purpose.",
  },
  {
    name: "Daniel Nelson",
    rating: 2,
    review:
      "Disappointed with this product. It had several problems and did not meet my expectations. The quality was poor and it stopped working quickly. I would not recommend it.",
  },
  {
    name: "Harper Carter",
    rating: 5,
    review:
      "Excellent product! It works flawlessly and the quality is outstanding. I am very satisfied with my purchase and the service I received. Highly recommended for anyone looking for this type of item.",
  },
  {
    name: "Lucas Mitchell",
    rating: 4,
    review:
      "Very good product with minor issues. It performs well and the quality is good. There are a few small drawbacks, but they don't detract from the overall positive experience. Worth the buy.",
  },
  {
    name: "Ella Perez",
    rating: 3,
    review:
      "The product is decent but not great. It works, but there are some areas where it could be improved. For the price, it's acceptable, but don't expect anything extraordinary.",
  },
  {
    name: "Henry Roberts",
    rating: 2,
    review:
      "Not satisfied with the product. It had multiple issues and did not perform well. The quality was lacking and it stopped working quickly. I would not recommend this product to others.",
  },
  {
    name: "Abigail Fisher",
    rating: 5,
    review:
      "I am very impressed with this product. It exceeded my expectations in every way. The quality is superb and it works perfectly. The customer service was also excellent. Highly recommended!",
  },
  {
    name: "Alexander Collins",
    rating: 4,
    review:
      "Good product with a few minor issues. It performs well and the quality is decent. There were a couple of small drawbacks, but overall, I am satisfied with my purchase.",
  },
  {
    name: "Zoe Ross",
    rating: 3,
    review:
      "Average product. It does the job but lacks some features and quality improvements. For the price, it's okay, but it's not exceptional. It meets basic needs but nothing more.",
  },
  {
    name: "Owen Sanchez",
    rating: 2,
    review:
      "Disappointed with this product. It didn't meet my expectations and had several issues. The quality was poor and it stopped working soon after purchase. I would not recommend this item.",
  },
  {
    name: "Mason Barnes",
    rating: 5,
    review:
      "Fantastic product! It works perfectly and the quality is excellent. I am extremely happy with my purchase and the customer service I received. Highly recommended for anyone looking for this type of product.",
  },
  {
    name: "Lily Murphy",
    rating: 4,
    review:
      "Very good product with a few minor flaws. It performs well and the quality is good. There are some small issues, but they don't significantly impact the overall experience. Worth the purchase.",
  },
  {
    name: "James Hughes",
    rating: 3,
    review:
      "Decent product but could use some improvements. It works, but there are areas where it falls short. For the price, it's acceptable, but it's not outstanding. It gets the job done.",
  },
  {
    name: "Madison Coleman",
    rating: 2,
    review:
      "Not happy with this product. It had multiple issues and didn't meet my expectations. The quality was poor, and it didn't perform as advertised. I wouldn't buy this again.",
  },
  {
    name: "Elijah Ward",
    rating: 5,
    review:
      "Exceptional product! It exceeded my expectations in every way. The build quality is superb and it works flawlessly. Highly recommended for anyone in the market for this item. Great experience overall.",
  },
  {
    name: "Avery Richardson",
    rating: 4,
    review:
      "Good product with minor issues. It performs well and the quality is decent. There were a couple of small drawbacks, but they don't detract from the overall positive experience. Satisfied with my purchase.",
  },
  {
    name: "Harper Brooks",
    rating: 3,
    review:
      "The product is average. It does its job but lacks some features and improvements. For the price, it's okay, but don't expect anything extraordinary. It meets basic needs.",
  },
  {
    name: "William Bailey",
    rating: 2,
    review:
      "Not satisfied with this product. It had several issues and didn't perform well. The quality was lacking and it stopped working quickly. I would not recommend this to others.",
  },
  {
    name: "Ella Gray",
    rating: 5,
    review:
      "Amazing product! It works flawlessly and the quality is exceptional. I am extremely pleased with my purchase and the service provided. Highly recommended for anyone considering this product.",
  },
  {
    name: "Michael Turner",
    rating: 4,
    review:
      "Very good product with a few minor issues. It performs well and the quality is solid. There were some small drawbacks, but overall, I am happy with my purchase. Worth the buy.",
  },
  {
    name: "Chloe Carter",
    rating: 3,
    review:
      "Average product. It works but could use some improvements. For the price, it's okay, but it's not outstanding. It serves its purpose but doesn't exceed expectations.",
  },
  {
    name: "Daniel Evans",
    rating: 2,
    review:
      "Disappointed with this product. It had several issues and didn't meet my expectations. The quality was poor and it stopped working quickly. I would not recommend this product.",
  },
  {
    name: "Sofia Stewart",
    rating: 5,
    review:
      "I am very impressed with this product. It exceeded all of my expectations in terms of performance and quality. The customer service was excellent, and I would definitely buy from this seller again.",
  },
  {
    name: "Joshua King",
    rating: 4,
    review:
      "Good product overall. It works well and the quality is decent. There are a few minor issues, but they don't impact the overall positive experience. I am satisfied with my purchase.",
  },
  {
    name: "Luna Sanders",
    rating: 3,
    review:
      "The product is decent but not great. It does its job but lacks some features and quality improvements. For the price, it's acceptable, but it's not exceptional. It meets basic needs.",
  },
  {
    name: "Henry Foster",
    rating: 2,
    review:
      "Not satisfied with the product. It had multiple issues and did not perform well. The quality was lacking, and it didn't live up to expectations. I would not recommend this item.",
  },
  {
    name: "Mia Collins",
    rating: 5,
    review:
      "Exceptional quality and performance. This product exceeded my expectations in every way. The build is solid and it works flawlessly. Highly recommended for anyone considering this product.",
  },
  {
    name: "Ethan Morris",
    rating: 4,
    review:
      "Very good product with some minor flaws. It works well and the quality is good. There were a few small issues, but they don't detract from the overall positive experience. Worth the buy.",
  },
  {
    name: "Ava Rogers",
    rating: 3,
    review:
      "The product is okay but could use some improvements. It functions as expected, but there are areas where it could be better. For the price, it's acceptable, but don't expect anything extraordinary.",
  },
  {
    name: "Jacob Bennett",
    rating: 2,
    review:
      "Not happy with this product. It had several issues and didn't meet my expectations. The quality was poor, and it didn't perform as advertised. I wouldn't buy this again.",
  },
  {
    name: "Ella Phillips",
    rating: 5,
    review:
      "I am extremely satisfied with this product. It works perfectly and the quality is outstanding. The customer service was also excellent. Highly recommended for anyone looking for this type of item.",
  },
  {
    name: "James Turner",
    rating: 4,
    review:
      "Good product with a few minor issues. It performs well and the quality is solid. There are some small drawbacks, but they don't significantly impact the overall positive experience. Happy with my purchase.",
  },
  {
    name: "Sophia Jenkins",
    rating: 3,
    review:
      "The product is average. It meets basic needs but lacks some features and quality improvements. For the price, it's acceptable, but it's not exceptional. It does the job.",
  },
  {
    name: "Michael Rivera",
    rating: 2,
    review:
      "Disappointing product. It had several issues and did not meet my expectations. The quality was poor and it stopped working quickly. I would not recommend this to others.",
  },
  {
    name: "Chloe Brooks",
    rating: 5,
    review:
      "Fantastic product! It exceeded all my expectations in terms of performance and quality. The customer service was also excellent. Highly recommended for anyone looking for this type of product.",
  },
  {
    name: "William Howard",
    rating: 4,
    review:
      "Very good product with a few minor issues. It works well and the quality is good. There were some small drawbacks, but they don't impact the overall positive experience. Satisfied with the purchase.",
  },
  {
    name: "Liam Davis",
    rating: 3,
    review:
      "The product is decent but not great. It works, but there are some areas where it could be improved. For the price, it's okay, but don't expect anything extraordinary. It meets basic needs.",
  },
  {
    name: "Zoe Wright",
    rating: 2,
    review:
      "Not satisfied with this product. It had multiple issues and didn't meet my expectations. The quality was lacking and it didn't perform well. I would not recommend this item.",
  },
  {
    name: "Aiden Clark",
    rating: 5,
    review:
      "Excellent product! It works perfectly and the quality is top-notch. I am very pleased with my purchase and the customer service provided. Highly recommended for anyone considering this product.",
  },
  {
    name: "Isabella Harris",
    rating: 4,
    review:
      "Good product overall. It performs well and the quality is decent. There are a few minor issues, but they don't detract from the overall positive experience. Worth the buy.",
  },
  {
    name: "Owen Allen",
    rating: 3,
    review:
      "The product is average. It does its job but lacks some features and improvements. For the price, it's acceptable, but it's not exceptional. It meets basic needs.",
  },
  {
    name: "Mia Lewis",
    rating: 2,
    review:
      "Disappointed with this product. It had several issues and did not meet my expectations. The quality was poor and it stopped working quickly. I would not recommend this product.",
  },
  {
    name: "Ethan Nelson",
    rating: 5,
    review:
      "I am very impressed with this product. It exceeded all my expectations in terms of performance and quality. The customer service was also excellent. Highly recommended for anyone in the market for this type of item.",
  },
];
